"use client";
import { FormEvent, useState } from "react";
import { API_URL } from "@/lib/api";
type Option = { id: string; name: string };
export function AdjustmentForm({ staff, products }: { staff: Option[]; products: Option[] }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!window.confirm("Post this adjustment? It cannot be edited after posting.")) return; setMessage(""); setError(""); const data = new FormData(event.currentTarget); const body = { product_id: data.get("product_id"), staff_id: data.get("staff_id") || null, quantity: data.get("quantity"), reason: data.get("reason"), idempotency_key: crypto.randomUUID() }; const response = await fetch(`${API_URL}/inventory/adjustments`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok) setError(json.error?.message ?? "Adjustment failed"); else { setMessage("Adjustment posted. Refresh to see updated balances."); event.currentTarget.reset(); } }
  return <form onSubmit={submit} className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Controlled adjustment</h2><p className="text-sm text-slate-500">Use a positive quantity to add stock or a negative quantity to remove it. Leave staff blank to adjust the warehouse.</p><select name="product_id" required className="w-full rounded-xl border px-4 py-3"><option value="">Product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="staff_id" className="w-full rounded-xl border px-4 py-3"><option value="">Warehouse</option>{staff.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="quantity" type="number" step="0.001" placeholder="Quantity (+ or −)" required /><textarea name="reason" minLength={3} maxLength={1000} required placeholder="Reason for correction" className="w-full rounded-xl border px-4 py-3" />{error && <p className="text-sm text-red-700">{error}</p>}{message && <p className="text-sm text-green-700">{message}</p>}<button className="rounded-xl border border-leaf-700 px-4 py-2 font-semibold text-leaf-700">Post adjustment</button></form>;
}
