import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { AdjustmentForm } from "@/components/adjustment-form";
import { AppShell } from "@/components/app-shell";
import { getCurrentUser, serverGet } from "@/lib/api";
type Warehouse = { product_id:string; product_name:string; unit_name:string; warehouse_in:string; issued:string; returned:string; adjustments:string; current_balance:string };
type StaffRow = { staff_id:string; staff_name:string; product_id:string; product_name:string; unit_name:string; total_issued:string; total_sold:string; total_returned:string; adjustments:string; current_balance:string };
type Options = { staff:{id:string;name:string}[]; products:{id:string;name:string}[] };
export default async function InventoryPage() { const cookie=(await cookies()).toString(); const user=await getCurrentUser(cookie); if(!user) redirect("/login"); if(user.role==="staff") redirect("/staff"); const [warehouse, staff, options]=await Promise.all([serverGet<Warehouse[]>("/inventory/warehouse",cookie),serverGet<StaffRow[]>("/inventory/staff-overview",cookie),serverGet<Options>("/inventory/options",cookie)]); return <AppShell user={user} title="Inventory"><section><h2 className="mb-3 font-semibold">Warehouse stock</h2><StockTable headers={["Product","Received","Issued","Returned","Adjustments","Balance"]} rows={warehouse.map(r=>[r.product_name,r.warehouse_in,r.issued,r.returned,r.adjustments,r.current_balance])} /></section><section className="mt-10"><h2 className="mb-3 font-semibold">Staff stock overview</h2><StockTable headers={["Staff","Product","Issued","Sold","Returned","Adjustments","Balance"]} rows={staff.map(r=>[r.staff_name,r.product_name,r.total_issued,r.total_sold,r.total_returned,r.adjustments,r.current_balance])} /></section><section className="mt-10 max-w-2xl"><AdjustmentForm {...options}/></section></AppShell>; }
function StockTable({headers,rows}:{headers:string[];rows:string[][]}) { return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-leaf-50 text-leaf-900"><tr>{headers.map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r,i)=><tr key={i} className="border-t">{r.map((v,j)=><td key={j} className={`px-4 py-3 ${j===r.length-1?"font-bold text-leaf-700":""}`}>{v}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-4 py-8 text-center text-slate-400">No stock movements yet</td></tr>}</tbody></table></div>; }
